name: Deploy Azure Infra via Terraform

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  deploy:
    name: Provision Infra with Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Set Azure subscription
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      # ===============================
    # Send Logs to Azure Monitor for workflow
    # ===============================
    - name: Send Deployment Logs to Azure Monitor
      if: always() # Run even if job fails
      run: |
        TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        STATUS="${{ job.status }}"
        MESSAGE="Terraform deployment finished with status: $STATUS"

        # Prepare log JSON
        LOG="{\"timestamp\":\"$TIMESTAMP\",\"workflow\":\"${{ github.workflow }}\",\"job\":\"${{ github.job }}\",\"status\":\"$STATUS\",\"message\":\"$MESSAGE\"}"

        # Create signature
        # Variables
        WORKSPACE_ID="${{ secrets.AZURE_LOG_ANALYTICS_WORKSPACE_ID }}"
        SHARED_KEY="${{ secrets.AZURE_LOG_ANALYTICS_SHARED_KEY }}"
        LOG_TYPE="GitHubActionsLogs"
        
        # Build string to sign
        BODY_LENGTH=$(echo -n $LOG | wc -c)
        RFC1123_DATE=$(date -u +"%a, %d %b %Y %H:%M:%S GMT")
        STRING_TO_SIGN="POST\n$BODY_LENGTH\napplication/json\nx-ms-date:$RFC1123_DATE\n/api/logs"
        
        # Generate signature (IMPORTANT: don't decode the key here, openssl needs base64 directly)
        SIGNATURE=$(echo -n "$STRING_TO_SIGN" | iconv -t utf8 | openssl dgst -sha256 -binary -hmac "$(echo -n $SHARED_KEY | base64 -d)" | base64)
        
        # Send log
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Log-Type: $LOG_TYPE" \
          -H "x-ms-date: $RFC1123_DATE" \
          -H "Authorization: SharedKey $WORKSPACE_ID:$SIGNATURE" \
          -d "$LOG" \
          "https://$WORKSPACE_ID.ods.opinsights.azure.com/api/logs?api-version=2016-04-01"

