name: Deploy Azure Infra via Terraform

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  deploy:
    name: Provision Infra with Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Set Azure subscription
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      # ===============================
    # Send Logs to Azure Monitor for workflow
    # ===============================
    - name: Send Deployment Logs to Azure Monitor
      if: always()
      shell: bash
      run: |
        WORKSPACE_ID="${{ secrets.AZURE_LOG_ANALYTICS_WORKSPACE_ID }}"
        SHARED_KEY="${{ secrets.AZURE_LOG_ANALYTICS_SHARED_KEY }}"
        LOG_TYPE="GitHubActions"
    
        PAYLOAD="{\"workflow\":\"${{ github.workflow }}\",\"job\":\"${{ github.job }}\",\"status\":\"${{ job.status }}\",\"timestamp\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}"
    
        CONTENT_LENGTH=$(printf '%s' "$PAYLOAD" | wc -c)
        RFC1123_DATE=$(date -u +"%a, %d %b %Y %H:%M:%S GMT")
    
        # REAL newlines, not "\n"
        STRING_TO_SIGN="POST
        $CONTENT_LENGTH
        application/json
        x-ms-date:$RFC1123_DATE
        /api/logs"
    
        DECODED_KEY=$(echo -n "$SHARED_KEY" | base64 --decode | tr -d '\0')
        SIGNATURE=$(printf '%s' "$STRING_TO_SIGN" | openssl dgst -sha256 -binary -hmac "$DECODED_KEY" | base64)
        AUTH_HEADER="SharedKey $WORKSPACE_ID:$SIGNATURE"
    
        echo "DEBUG: STRING_TO_SIGN:"
        printf '%s\n' "$STRING_TO_SIGN"
        echo "DEBUG: SIGNATURE=$SIGNATURE"
    
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Log-Type: $LOG_TYPE" \
          -H "x-ms-date: $RFC1123_DATE" \
          -H "Authorization: $AUTH_HEADER" \
          --data "$PAYLOAD" \
          "https://$WORKSPACE_ID.ods.opinsights.azure.com/api/logs?api-version=2016-04-01"


