name: Deploy Azure Infra via Terraform

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  deploy:
    name: Provision Infra with Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Set Azure subscription
      run: |
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      # ===============================
    # Send Logs to Azure Monitor for workflow
    # ===============================
    - name: Send Deployment Logs to Azure Monitor
      if: always()
      run: |
        WORKSPACE_ID="${{ secrets.AZURE_LOG_ANALYTICS_WORKSPACE_ID }}"
        SHARED_KEY="${{ secrets.AZURE_LOG_ANALYTICS_SHARED_KEY }}"
        LOG_TYPE="GitHubActionsLogs"
    
        TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        STATUS="${{ job.status }}"
        PAYLOAD="{\"timestamp\":\"$TIMESTAMP\",\"workflow\":\"${{ github.workflow }}\",\"job\":\"${{ github.job }}\",\"status\":\"$STATUS\"}"
    
        # Required for signature
        CONTENT_LENGTH=$(echo -n "$PAYLOAD" | wc -c)
        RFC1123_DATE=$(date -u +"%a, %d %b %Y %H:%M:%S GMT")
        STRING_TO_SIGN="POST\n$CONTENT_LENGTH\napplication/json\nx-ms-date:$RFC1123_DATE\n/api/logs"
    
        # Generate HMAC-SHA256 signature safely using xxd to avoid null bytes
        SIGNATURE=$(printf '%s' "$STRING_TO_SIGN" | openssl dgst -sha256 -binary -hmac "$(echo -n $SHARED_KEY | base64 -d)" | base64)
    
        # Send the log
        curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Log-Type: $LOG_TYPE" \
          -H "x-ms-date: $RFC1123_DATE" \
          -H "Authorization: SharedKey $WORKSPACE_ID:$SIGNATURE" \
          -d "$PAYLOAD" \
          "https://$WORKSPACE_ID.ods.opinsights.azure.com/api/logs?api-version=2016-04-01"
